export interface Property {
    property_id: number;
    user_id: number;
    property_type_id: number;
    title: string;
    description: string;
    short_description: string;
    listing_type: string;
    status: string;
    price: number;
    currency: string;
    // price_per_sqm: number;
    is_negotiable: boolean;
    bedrooms: number;
    bathrooms: number;
    area_sqm: number;
    floor_number: number;
    total_floors: number;
    year_built: number;
    furnished_type: string;
    has_parking: boolean;
    has_balcony: boolean;
    has_garden: boolean;
    has_elevator: boolean;
    has_garage: boolean;
    street: string;
    city: string;
    // region: string;
    country: string;
    post_code: string;
    latitude: number;
    longitude: number;
    views_count: number;
    favorites_count: number;
    inquiries_count: number;
    created_at: Date;
    updated_at: Date;
    published_at: Date;
    expires_at: Date;
}